### PR TITLE
Show tag name when detached status if possible

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by mcornella** [comment]
I haven't been able to reliably use `git describe --all`. This will output either:
- The tag or branch name if we're in one (even if we're in detached mode):

```
> tags/tag
> heads/wkentaro-fix-git-prompt-plugin
```
- The commit relative to the closest ancestor tagged or with a branch head. Examples:

```
> tags/tag-1-g636d72f
> heads/wkentaro-fix-git-prompt-plugin-1-g636d72f
```
- Fail if no ancestor is tagged or has branch head (for instance, `master~1`):

```
$ git describe --all
fatal: No tags can describe 'a207a38d634cc10441636bc4359cd8a18c502dea'.
Try --always, or create some tags.
```

Because of the `split('-g')`, sometimes names will get cut off, as in the time we're in detached mode in the last commit of the branch `fix-git-prompt-plugin`, which will look like `it-prompt-plugin`.

---

I've been looking for other alternatives to get _both_ the commit hash and tag if it is there, and the only solution which only uses one call to git is `git log -1 --format="%h %d"`.

This will look like the following:

```
# untagged commit, detached mode
$ git log -n 1 --format="%h %d"
5649482  (HEAD, wkentaro/fix-git-prompt-plugin, wkentaro-fix-git-prompt-plugin)
# tagged commit, detached mode
$ git log -n 1 --format="%h %d"
5649482  (HEAD, tag: tag-name, wkentaro/fix-git-prompt-plugin, wkentaro-fix-git-prompt-plugin)
```

so we can get the commit hash with `.split(' ')[0]` and get the tag-name using a regexp.

**Comment by wkentaro** [comment]
In my env, I cannot reproduce

> Fail if no ancestor is tagged or has branch head (for instance, master~1):

```
% git checkout master~1
HEAD is now at 53f68b4... change wstool_cd alias
% git describe --all
replace/ae406b44fa385d0bab42e54ffb0aeefbc4f66e80-260-g53f68b4
```

> Because of the split('-g'), sometimes names will get cut off, as in the time we're in detached mode in the last commit of the branch fix-git-prompt-plugin, which will look like it-prompt-plugin.

this function `get_detached_status_name()` should be called **detached** status.
so, the output should be 
1. `replace/ae406b44fa385d0bab42e54ffb0aeefbc4f66e80-260-g53f68b4` 
2.  `tags/tag`
3.  `tags/tag-1-g636d72f`

as far as I know. current function does work in all situations.

As a special situation,
if user have tag named with `-g` like `tag-gat`, the output will be like ``tags/tag-gat-1-g636d72f`. In this case, current function returns output (that will be `tags/tag-gat-1-g636d72f`) as unexpected one, but changing it to find `-g` from back can solve that problem.

**Comment by wkentaro** [comment]
> In my env, I cannot reproduce

I did reproduce.
In a new repository which has few commits it happen.

**Comment by wkentaro** [comment]
I updated the commit.
I think latest function can cope with all of situations you listed above. @mcornella

**Comment by wkentaro** [comment]
The reason I prefer `git describe` is it seems that `vcs_info` also uses it.
I'm using `vcs_info` now and it shows `tags/0.1.6` when I am at tag, and this is same output of `git describe --all`.

**Comment by mcornella** [comment]
Here's how `vcs_info` uses the `git describe` command: [zsh-users/zsh@/Functions/VCS_Info/Backends/VCS_INFO_get_data_git#L105](https://github.com/zsh-users/zsh/blob/master/Functions/VCS_Info/Backends/VCS_INFO_get_data_git#L105):

> ``` zsh
> git describe --all --exact-match HEAD 2>/dev/null
> ```
> 
> Which only returns the tag name if there is an **exact** tag name to be returned (it also returns the branch name as well). They don't get the weird `tags/tagname-N-hash` output that way, so I suggest:
1. We use that command in combination of `git rev-parse --short HEAD` to get the commit hash
2. We use a combination that will enable us to get both, _i.e._ `git log -1 --format="%h%d"`.

Your test suite lacks the case where the tag name is `tag-gat` and is an exact-match for HEAD, in which case the output will be like `tags/tag-gat` which will output `at` because that is presumably the part of the hash.

**Comment by wkentaro** [comment]
> Your test suite lacks the case where the tag name is tag-gat and is an exact-match for HEAD, in which case the output will be like tags/tag-gat which will output at because that is presumably the part of the hash.

Oops, you're right, thanks.
I tried the two ways to get hash and refname.
https://gist.github.com/wkentaro/f7320d112782c1edb188
And in most cases, using `git log` is faster than the other.

I'm going to implement this with `git log`.

**Comment by wkentaro** [comment]
I've implemented new ver func with `git log`.
See: #4

**Pull request closed without merging**
